language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t degas1980/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true degas1980/docker-react npm run test -- --coverage
  